---

services:
  app:
    image: louislam/uptime-kuma:2
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=${TRAEFIK_HOST_RULE}"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.tls.certresolver=letsencrypt"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
    volumes:
      - data:/app/data
    restart: always

networks:
  proxy:
    external: true

volumes:
  data: